name: Release

on:
  workflow_run:
    workflows:
      - "Test"
    branches:
      - master
    types:
      - completed


jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: ${{ contains(toJSON(github.event.commits.*.message), '[ci release]') && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Git Fetch Unshallow
        run: git fetch --prune --unshallow

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: Refresh pkg.go.dev
        uses: andrewslotin/go-proxy-pull-action@master